# This is a basic workflow to help you get started with Actions

name: Test build
#
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the stage branch
on:
  push:
    tags:
      - integration

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [22.12.0]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "22.12.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Installing packages
        run: npm install

      - name: Building Nuxt app
        run: npm run generate
        # env:
        #   CI: true
        #   NODE_ENV: integration
        #   SERVER_ENV: integration
        #   HYBRID_APP_URL: ${{ secrets.INTEGRATION_HYBRID_APP_URL }}
        #   VERLOOP_DOMAIN: ${{ secrets.VERLOOP_TEST_DOMAIN }}
        #   FIREBASE_SERVER_TOKEN: ${{ secrets.CUSTOM_EVENT_TRACK_TOKEN }}
        #   RENTO_NEXT_BASE_URL: https://rentomojo-nxt-integration.rentomojo.com

      - name: Deploy static site to S3 test-nuxt-app bucket
        run: aws s3 sync ./dist/ s3://test-nuxt-app --delete

      - name: All run done
        run: echo Astalavista
